name: Give a name anything 

on:
  workflow_dispatch:
  push:
    branches: [main] #this sets it up so that we run our workflows any time that we push a commit

#adding a comment here to try to re push this commit 

jobs:
  test_my_django_project:
    runs-on: ubuntu-latest
    # env: 
    #   DJANGO_SECRET_KEY: "this-is-it"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run hello World
      run: | #we can run secrets.DJANGO_SECRET_KEY below because the new secret key is stored in github secrets
        echo "DJANGO_SECRET_KEY IS: ${{ secrets.DJANGO_SECRET_KEY }}" 
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install requirements
      run: |
        python -m pip install pip --upgrade
        python -m pip install -r requirements.txt    
    - name: Run Tests
      run: |
        python3.10 manage.py test

