name: Give a name anything 

on:
  workflow_call:
    secrets:
    DJANGO_SECRET_KEY:
      required: true
  workflow_dispatch:
  # push:
  #   branches: [main] #this sets it up so that we run our workflows any time that we push a commit

#adding a comment here to try to re push this commit 

jobs:
  test_my_django_project:
    runs-on: ubuntu-latest
    env: 
      DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello World
        run: | 
          echo "DJANGO_SECRET_KEY IS: ${{ env.DJANGO_SECRET_KEY }}" 
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt    
      - name: Run Tests
        run: |
          python3.10 manage.py test

